//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictionaryMusicalCliente.PictionaryServidorServicioCuenta {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReenvioCodigoVerificacionDTO", Namespace="http://schemas.datacontract.org/2004/07/global::Servicios.Contratos.DTOs")]
    [System.SerializableAttribute()]
    public partial class ReenvioCodigoVerificacionDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string TokenCodigoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string TokenCodigo {
            get {
                return this.TokenCodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenCodigoField, value) != true)) {
                    this.TokenCodigoField = value;
                    this.RaisePropertyChanged("TokenCodigo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfirmacionCodigoDTO", Namespace="http://schemas.datacontract.org/2004/07/global::Servicios.Contratos.DTOs")]
    [System.SerializableAttribute()]
    public partial class ConfirmacionCodigoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodigoIngresadoField;
        
        private string TokenCodigoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CodigoIngresado {
            get {
                return this.CodigoIngresadoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoIngresadoField, value) != true)) {
                    this.CodigoIngresadoField = value;
                    this.RaisePropertyChanged("CodigoIngresado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string TokenCodigo {
            get {
                return this.TokenCodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenCodigoField, value) != true)) {
                    this.TokenCodigoField = value;
                    this.RaisePropertyChanged("TokenCodigo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PictionaryServidorServicioCuenta.ICuentaManejador")]
    public interface ICuentaManejador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentaManejador/SolicitarCodigoVerificacion", ReplyAction="http://tempuri.org/ICuentaManejador/SolicitarCodigoVerificacionResponse")]
        global::Servicios.Contratos.DTOs.ResultadoSolicitudCodigoDTO SolicitarCodigoVerificacion(global::Servicios.Contratos.DTOs.NuevaCuentaDTO nuevaCuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentaManejador/SolicitarCodigoVerificacion", ReplyAction="http://tempuri.org/ICuentaManejador/SolicitarCodigoVerificacionResponse")]
        System.Threading.Tasks.Task<global::Servicios.Contratos.DTOs.ResultadoSolicitudCodigoDTO> SolicitarCodigoVerificacionAsync(global::Servicios.Contratos.DTOs.NuevaCuentaDTO nuevaCuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentaManejador/ReenviarCodigoVerificacion", ReplyAction="http://tempuri.org/ICuentaManejador/ReenviarCodigoVerificacionResponse")]
        global::Servicios.Contratos.DTOs.ResultadoSolicitudCodigoDTO ReenviarCodigoVerificacion(PictionaryMusicalCliente.PictionaryServidorServicioCuenta.ReenvioCodigoVerificacionDTO solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentaManejador/ReenviarCodigoVerificacion", ReplyAction="http://tempuri.org/ICuentaManejador/ReenviarCodigoVerificacionResponse")]
        System.Threading.Tasks.Task<global::Servicios.Contratos.DTOs.ResultadoSolicitudCodigoDTO> ReenviarCodigoVerificacionAsync(PictionaryMusicalCliente.PictionaryServidorServicioCuenta.ReenvioCodigoVerificacionDTO solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentaManejador/ConfirmarCodigoVerificacion", ReplyAction="http://tempuri.org/ICuentaManejador/ConfirmarCodigoVerificacionResponse")]
        global::Servicios.Contratos.DTOs.ResultadoRegistroCuentaDTO ConfirmarCodigoVerificacion(PictionaryMusicalCliente.PictionaryServidorServicioCuenta.ConfirmacionCodigoDTO confirmacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentaManejador/ConfirmarCodigoVerificacion", ReplyAction="http://tempuri.org/ICuentaManejador/ConfirmarCodigoVerificacionResponse")]
        System.Threading.Tasks.Task<global::Servicios.Contratos.DTOs.ResultadoRegistroCuentaDTO> ConfirmarCodigoVerificacionAsync(PictionaryMusicalCliente.PictionaryServidorServicioCuenta.ConfirmacionCodigoDTO confirmacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentaManejador/RegistrarCuenta", ReplyAction="http://tempuri.org/ICuentaManejador/RegistrarCuentaResponse")]
        global::Servicios.Contratos.DTOs.ResultadoRegistroCuentaDTO RegistrarCuenta(global::Servicios.Contratos.DTOs.NuevaCuentaDTO nuevaCuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentaManejador/RegistrarCuenta", ReplyAction="http://tempuri.org/ICuentaManejador/RegistrarCuentaResponse")]
        System.Threading.Tasks.Task<global::Servicios.Contratos.DTOs.ResultadoRegistroCuentaDTO> RegistrarCuentaAsync(global::Servicios.Contratos.DTOs.NuevaCuentaDTO nuevaCuenta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICuentaManejadorChannel : PictionaryMusicalCliente.PictionaryServidorServicioCuenta.ICuentaManejador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CuentaManejadorClient : System.ServiceModel.ClientBase<PictionaryMusicalCliente.PictionaryServidorServicioCuenta.ICuentaManejador>, PictionaryMusicalCliente.PictionaryServidorServicioCuenta.ICuentaManejador {
        
        public CuentaManejadorClient() {
        }
        
        public CuentaManejadorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CuentaManejadorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CuentaManejadorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CuentaManejadorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public global::Servicios.Contratos.DTOs.ResultadoSolicitudCodigoDTO SolicitarCodigoVerificacion(global::Servicios.Contratos.DTOs.NuevaCuentaDTO nuevaCuenta) {
            return base.Channel.SolicitarCodigoVerificacion(nuevaCuenta);
        }
        
        public System.Threading.Tasks.Task<global::Servicios.Contratos.DTOs.ResultadoSolicitudCodigoDTO> SolicitarCodigoVerificacionAsync(global::Servicios.Contratos.DTOs.NuevaCuentaDTO nuevaCuenta) {
            return base.Channel.SolicitarCodigoVerificacionAsync(nuevaCuenta);
        }
        
        public global::Servicios.Contratos.DTOs.ResultadoSolicitudCodigoDTO ReenviarCodigoVerificacion(PictionaryMusicalCliente.PictionaryServidorServicioCuenta.ReenvioCodigoVerificacionDTO solicitud) {
            return base.Channel.ReenviarCodigoVerificacion(solicitud);
        }
        
        public System.Threading.Tasks.Task<global::Servicios.Contratos.DTOs.ResultadoSolicitudCodigoDTO> ReenviarCodigoVerificacionAsync(PictionaryMusicalCliente.PictionaryServidorServicioCuenta.ReenvioCodigoVerificacionDTO solicitud) {
            return base.Channel.ReenviarCodigoVerificacionAsync(solicitud);
        }
        
        public global::Servicios.Contratos.DTOs.ResultadoRegistroCuentaDTO ConfirmarCodigoVerificacion(PictionaryMusicalCliente.PictionaryServidorServicioCuenta.ConfirmacionCodigoDTO confirmacion) {
            return base.Channel.ConfirmarCodigoVerificacion(confirmacion);
        }
        
        public System.Threading.Tasks.Task<global::Servicios.Contratos.DTOs.ResultadoRegistroCuentaDTO> ConfirmarCodigoVerificacionAsync(PictionaryMusicalCliente.PictionaryServidorServicioCuenta.ConfirmacionCodigoDTO confirmacion) {
            return base.Channel.ConfirmarCodigoVerificacionAsync(confirmacion);
        }
        
        public global::Servicios.Contratos.DTOs.ResultadoRegistroCuentaDTO RegistrarCuenta(global::Servicios.Contratos.DTOs.NuevaCuentaDTO nuevaCuenta) {
            return base.Channel.RegistrarCuenta(nuevaCuenta);
        }
        
        public System.Threading.Tasks.Task<global::Servicios.Contratos.DTOs.ResultadoRegistroCuentaDTO> RegistrarCuentaAsync(global::Servicios.Contratos.DTOs.NuevaCuentaDTO nuevaCuenta) {
            return base.Channel.RegistrarCuentaAsync(nuevaCuenta);
        }
    }
}
