//------------------------------------------------------------------------------
// <auto-generated>
//     Este codigo se genero a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicacion.
//     Los cambios manuales en este archivo se sobrescribiran si se regenera el codigo.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Amigo
    {
        public bool Estado { get; set; }
        public int UsuarioEmisor { get; set; }
        public int UsuarioReceptor { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
