//------------------------------------------------------------------------------
// <auto-generated>
//     Este cÃ³digo se generÃ³ a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicaciÃ³n.
//     Los cambios manuales en este archivo se sobrescribirÃ¡n si se regenera el cÃ³digo.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Amigo
    {
        public bool Estado { get; set; }
        public int UsuarioEmisor { get; set; }
        public int UsuarioReceptor { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
