//------------------------------------------------------------------------------
// <auto-generated>
//     Este cÃ³digo se generÃ³ a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicaciÃ³n.
//     Los cambios manuales en este archivo se sobrescribirÃ¡n si se regenera el cÃ³digo.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictionaryMusicalServidor.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancion
    {
        public int idCancion { get; set; }
        public string Nombre { get; set; }
        public string Cancion_Ruta { get; set; }
        public string Idioma { get; set; }
        public int Artista_idArtista { get; set; }
        public int Genero_idGenero { get; set; }
    
        public virtual Artista Artista { get; set; }
        public virtual Genero Genero { get; set; }
    }
}
