//------------------------------------------------------------------------------
// <auto-generated>
//     Este cÃ³digo se generÃ³ a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicaciÃ³n.
//     Los cambios manuales en este archivo se sobrescribirÃ¡n si se regenera el cÃ³digo.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictionaryMusicalServidor.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expulsion
    {
        public int idExpulsion { get; set; }
        public string Causa { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Jugador_idJugador { get; set; }
    
        public virtual Jugador Jugador { get; set; }
    }
}
